name: Continuous Integration

on:
  push:
    branches:
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm test
      working-directory: ./spa_react
