name: Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
    - name: Install dependencies
      run: npm install
      working-directory: ./spa_react
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }}
        -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image(react)
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mucahitfindik/spa_react
        dockerfile: ./spa_react/Dockerfile
        directory: spa_react
        tags: v1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
